Repository Azure/azure-sdk-for-ruby, pull requests merged in 2018-05, with the labels that each got.

#1301 Restructure repository structure
  CODEOWNERS
  Rakefile
  azure_sdk/azure_sdk.gemspec
  config/GEMS_TO_RELEASE
  config/GEM_VERSIONS
  config/config.json
  config/dir_metadata.json
  config/profiles.json
  management/azure_mgmt_signalr/lib/azure_mgmt_signalr.rb
  management/azure_mgmt_signalr/lib/profiles/.gitignore
Labels: review

#1302 Bump Signalr version
  ChangeLog.md
  config/GEMS_TO_RELEASE
  config/GEM_VERSIONS
  management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/signal_rmanagement_client.rb
  management/azure_mgmt_signalr/lib/version.rb
Labels: review

#1303 Container service fix
  ChangeLog.md
  azure_sdk/lib/azure_sdk/version.rb
  azure_sdk/lib/latest/modules/containerservice_profile_module.rb
  config/GEMS_TO_RELEASE
  config/GEM_VERSIONS
  config/config.json
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/container_service_client.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/container_service_client.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/container_services.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/container_service_client.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/container_services.rb
  management/azure_mgmt_container_service/lib/profiles/latest/modules/containerservice_profile_module.rb
  management/azure_mgmt_container_service/lib/version.rb
Labels: review

#1315 [AutoPR servermanagement/resource-manager] Fix Python conf of servermanager
  azure_sdk/lib/azure_sdk.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/gateway.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/encryption_jwk_resource.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/error.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/gateway_parameters.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/gateway_profile.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/gateway_resource.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/gateway_resources.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/gateway_status.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/node_parameters.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/node_resource.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/node_resources.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_command_parameters.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_command_result.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_command_results.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_command_status.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_session_resource.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_session_resources.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_tab_completion_parameters.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/power_shell_tab_completion_results.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/prompt_field_description.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/prompt_message_response.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/resource.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/session_parameters.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/session_resource.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/models/version.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/node.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/power_shell.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/server_management.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/session.rb
  management/azure_mgmt_server_management/lib/2016-07-01-preview/generated/azure_mgmt_server_management/version.rb
Labels: RestPRMerged, review

#1333 [AutoPR automation/resource-manager] Refactoring Job Definitions
  azure_sdk/lib/latest/modules/automation_profile_module.rb
  management/azure_mgmt_automation/lib/2015-10-31/generated/azure_mgmt_automation.rb
  management/azure_mgmt_automation/lib/2015-10-31/generated/azure_mgmt_automation/models/hybrid_runbook_worker_group.rb
  management/azure_mgmt_automation/lib/profiles/latest/modules/automation_profile_module.rb
Labels: RestPRMerged
