Repository Azure/azure-sdk-for-ruby, pull requests merged in 2018-06, with the labels that each got.

#1311 [AutoPR containerservices/resource-manager] [AKS] add new 2018-03-31 API
  azure_sdk/lib/azure_sdk.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/container_service_client.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/container_services.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_agent_pool_profile.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_diagnostics_profile.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_linux_profile.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_list_result.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_master_profile.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_orchestrator_profile.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_ssh_configuration.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_ssh_public_key.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_vmdiagnostics.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/container_service_windows_profile.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/models/resource.rb
  management/azure_mgmt_container_service/lib/2016-03-30/generated/azure_mgmt_container_service/version.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/container_service_client.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/container_services.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_agent_pool_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_custom_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_diagnostics_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_linux_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_list_result.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_master_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_orchestrator_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_service_principal_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_ssh_configuration.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_ssh_public_key.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_vmdiagnostics.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/container_service_windows_profile.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/models/resource.rb
  management/azure_mgmt_container_service/lib/2016-09-30/generated/azure_mgmt_container_service/version.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/container_service_client.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/container_services.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_agent_pool_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_custom_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_diagnostics_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_linux_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_list_result.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_master_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_orchestrator_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_service_principal_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_ssh_configuration.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_ssh_public_key.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_vmdiagnostics.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/container_service_windows_profile.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/models/resource.rb
  management/azure_mgmt_container_service/lib/2017-01-31/generated/azure_mgmt_container_service/version.rb
Labels: RestPRMerged

#1356 [AutoPR network/resource-manager] Add primary flag to 2015-06-15 NetworkInterfaceIPConfiguration
  management/azure_mgmt_network/lib/2015-06-15/generated/azure_mgmt_network/models/network_interface_ipconfiguration.rb
Labels: RestPRMerged

#1364 [AutoPR cognitiveservices/data-plane/ComputerVision] Add Spanish as an option as ServiceLanguage for ComputerVision
  data/azure_cognitiveservices_computervision/lib/1.0/generated/azure_cognitiveservices_computervision/computer_vision_client.rb
Labels: RestPRMerged, review

#1371 [AutoPR containerinstance/resource-manager] Container Instance - Fix Mistake in June Update
  management/azure_mgmt_container_instance/lib/azure_mgmt_container_instance.rb
Labels: RestPRMerged, review

#1372 [AutoPR] containerinstance/resource-manager
  management/azure_mgmt_container_instance/lib/azure_mgmt_container_instance.rb
Labels: ServicePR, review

#1373 [AutoPR network/resource-manager] network: add https probe which was missing in the spec
  management/azure_mgmt_network/lib/azure_mgmt_network.rb
Labels: RestPRMerged

#1378 [AutoPR cognitiveservices/data-plane/ComputerVision] Update CognitiveService ComputerVision API to V2
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/computer_vision_client.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/adult_info.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/azure_regions.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/category.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/category_detail.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/celebrities_model.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/celebrity_results.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/color_info.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/computer_vision_error.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/computer_vision_error_codes.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/details.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/domain_model_results.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/face_description.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/face_rectangle.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/gender.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_analysis.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_caption.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_description.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_description_details.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_metadata.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_tag.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_type.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_url.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/landmark_results.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/landmark_results_landmarks_item.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/landmarks_model.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/line.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/list_models_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/model_description.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_languages.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_line.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_region.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_word.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/recognition_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/tag_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/text_operation_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/text_operation_status_codes.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/text_recognition_mode.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/visual_feature_types.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/word.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/module_definition.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/version.rb
  data/azure_cognitiveservices_computervision/lib/azure_cognitiveservices_computervision.rb
Labels: RestPRMerged, review

#1382 [AutoPR] sql/resource-manager
  azure_sdk/lib/latest/modules/sql_profile_module.rb
  management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql.rb
  management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/security_alert_policy_state.rb
  management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/server_security_alert_policy.rb
  management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/sql_management_client.rb
  management/azure_mgmt_sql/lib/profiles/latest/modules/sql_profile_module.rb
Labels: ServicePR, review

#1383 [AutoPR] cognitiveservices/data-plane/ComputerVision
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/computer_vision_client.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/adult_info.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/azure_regions.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/category.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/category_detail.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/celebrities_model.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/celebrity_results.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/color_info.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/computer_vision_error.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/computer_vision_error_codes.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/details.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/domain_model_results.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/face_description.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/face_rectangle.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/gender.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_analysis.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_caption.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_description.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_description_details.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_metadata.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_tag.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_type.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_url.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/landmark_results.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/landmark_results_landmarks_item.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/landmarks_model.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/line.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/list_models_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/model_description.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_languages.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_line.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_region.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/ocr_word.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/recognition_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/tag_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/text_operation_result.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/text_operation_status_codes.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/text_recognition_mode.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/visual_feature_types.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/word.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/module_definition.rb
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/version.rb
  data/azure_cognitiveservices_computervision/lib/azure_cognitiveservices_computervision.rb
Labels: ServicePR, review

#1385 [AutoPR] compute/resource-manager
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/data_disk.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/osdisk.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/rollback_status_info.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_scale_set_osdisk.rb
  management/azure_mgmt_compute/lib/azure_mgmt_compute.rb
Labels: ServicePR, review

#1391 [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint
  data/azure_cognitiveservices_computervision/lib/2.0/generated/azure_cognitiveservices_computervision/models/image_tag.rb
Labels: RestPRMerged, review

#1399 [AutoPR apimanagement/resource-manager] Fix contract for Error in OperationResultContract
  management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management.rb
  management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/error_response_body.rb
  management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/operation_result_contract.rb
Labels: RestPRMerged, review

#1410 [AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties
  management/azure_mgmt_storage/lib/2015-05-01-preview/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2015-06-15/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2016-01-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/endpoints.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account_create_parameters.rb
  management/azure_mgmt_storage/lib/azure_mgmt_storage.rb
Labels: RestPRMerged, review

#1423 [AutoPR storage/resource-manager] Minor update to version
  management/azure_mgmt_storage/lib/2015-05-01-preview/generated/azure_mgmt_storage/version.rb
  management/azure_mgmt_storage/lib/2015-06-15/generated/azure_mgmt_storage/version.rb
  management/azure_mgmt_storage/lib/2016-01-01/generated/azure_mgmt_storage/version.rb
  management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/version.rb
  management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/version.rb
  management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/version.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/version.rb
Labels: RestPRMerged, review

#1425 Release srp storage
  ChangeLog.md
  config/GEMS_TO_RELEASE
  config/GEM_VERSIONS
  config/config.json
  management/azure_mgmt_storage/lib/2015-05-01-preview/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2015-06-15/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2016-01-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2016-12-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2017-06-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2017-10-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/endpoints.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/models/storage_account_create_parameters.rb
  management/azure_mgmt_storage/lib/2018-02-01/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/2018-03-01-preview/generated/azure_mgmt_storage/models/endpoints.rb
  management/azure_mgmt_storage/lib/2018-03-01-preview/generated/azure_mgmt_storage/models/storage_account.rb
  management/azure_mgmt_storage/lib/2018-03-01-preview/generated/azure_mgmt_storage/models/storage_account_create_parameters.rb
  management/azure_mgmt_storage/lib/2018-03-01-preview/generated/azure_mgmt_storage/storage_management_client.rb
  management/azure_mgmt_storage/lib/version.rb
Labels: review

#1434 [AutoPR servicebus/resource-manager] ServiceBus: Removed space from pendingReplicationOperationsCount
  management/azure_mgmt_service_bus/lib/2017-04-01/generated/azure_mgmt_service_bus/models/arm_disaster_recovery.rb
  management/azure_mgmt_service_bus/lib/2017-04-01/generated/azure_mgmt_service_bus/models/migration_config_properties.rb
Labels: RestPRMerged, review

#1421 [AutoPR compute/resource-manager] Swagger change for getting all availability sets in a subscription and StandardSSD
  management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/availability_sets.rb
  management/azure_mgmt_compute/lib/2015-06-15/generated/azure_mgmt_compute/models/availability_set_list_result.rb
  management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/availability_sets.rb
  management/azure_mgmt_compute/lib/2016-03-30/generated/azure_mgmt_compute/models/availability_set_list_result.rb
  management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/availability_sets.rb
  management/azure_mgmt_compute/lib/2016-04-30-preview/generated/azure_mgmt_compute/models/availability_set_list_result.rb
  management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/availability_sets.rb
  management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/models/availability_set_list_result.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/availability_sets.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/availability_set_list_result.rb
  management/azure_mgmt_compute/lib/2018-04-01/generated/azure_mgmt_compute/models/disk_sku.rb
  management/azure_mgmt_compute/lib/2018-04-01/generated/azure_mgmt_compute/models/storage_account_types.rb
Labels: RestPRMerged, review
