Repository Azure/azure-sdk-for-ruby, pull requests merged in 2018-08, with the labels that each got.

#1548 [AutoPR sql/resource-manager] fix SQL VA command copy paste typo
  management/azure_mgmt_sql/lib/2017-03-01-preview/generated/azure_mgmt_sql/models/database_vulnerability_assessment.rb
Labels: RestPRMerged, review

#1549 [AutoPR monitor/resource-manager] [Monitor] Fix issue #3585: revert previous commit since it is a brealing change
  azure_sdk/lib/latest/modules/monitor_profile_module.rb
  management/azure_mgmt_monitor/lib/2015-04-01/generated/azure_mgmt_monitor.rb
  management/azure_mgmt_monitor/lib/2015-04-01/generated/azure_mgmt_monitor/models/recurrence.rb
  management/azure_mgmt_monitor/lib/profiles/latest/modules/monitor_profile_module.rb
Labels: RestPRMerged, review

#1551 [AutoPR apimanagement/resource-manager] Bug fix on readonly property
  management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/certificate_configuration.rb
Labels: RestPRMerged, review

#1569 [AutoPR apimanagement/resource-manager] Make 2018-01-01 as default for all clients
  management/azure_mgmt_api_management/lib/2018-01-01/generated/azure_mgmt_api_management/models/hostname_configuration.rb
Labels: RestPRMerged, review

#1586 Bug fix for azure sdk
  ChangeLog.md
  azure_sdk/azure_sdk.gemspec
  azure_sdk/lib/azure_sdk.rb
  azure_sdk/lib/azure_sdk/version.rb
  config/GEMS_TO_RELEASE
  config/GEM_VERSIONS
  generators/requirefilegen/src/require_file_generator.rb
Labels: review

#1576 [AutoPR compute/resource-manager] [Compute] add zone and rolling upgrade.
  azure_sdk/lib/latest/modules/compute_profile_module.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_scale_set_vm.rb
  management/azure_mgmt_compute/lib/2017-12-01/generated/azure_mgmt_compute/models/virtual_machine_update.rb
  management/azure_mgmt_compute/lib/2018-04-01/generated/azure_mgmt_compute/models/access_uri.rb
  management/azure_mgmt_compute/lib/profiles/latest/modules/compute_profile_module.rb
Labels: RestPRMerged, review

#1591 [AutoPR signalr/resource-manager] return more perperties of SignalR resource
  azure_sdk/lib/latest/modules/signalr_profile_module.rb
  management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr.rb
  management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/dimension.rb
  management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/metric_specification.rb
  management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rkeys.rb
  management/azure_mgmt_signalr/lib/2018-03-01-preview/generated/azure_mgmt_signalr/models/signal_rresource.rb
  management/azure_mgmt_signalr/lib/profiles/latest/modules/signalr_profile_module.rb
Labels: RestPRMerged, review

#1602 [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.
  management/azure_mgmt_automation/lib/2015-10-31/generated/azure_mgmt_automation/dsc_configuration_operations.rb
Labels: RestPRMerged
